### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by spinx** [elliotboney/thinkific-php#1]
Can you publish this library to packagist so that I can include it easily via composer ? It's not there ATM.

**Comment by elliotboney** [comment]
Sure!

**Comment by spinx** [comment]
Thanks a bunch. And thanks for publishing it on github in the first place. Much appreciated!

**Comment by elliotboney** [comment]
It's up on packagist! Let me know if it needs anything. I use it for work
but really for only part of the api
